# Generated by Django 3.2.7 on 2021-10-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('picture', models.ImageField(upload_to='apiapp\\static\\pic_sample')),
            ],
        ),
        migrations.CreateModel(
            name='person_in_the_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
